version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release
      ARCH_ARG: "-A x64"

clone_script:
  - cmd: git clone --recursive -q --branch=main https://github.com/PatrickTorgerson/Envy.git C:\projects\envy

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"