version: '{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      GENERATOR: "Visual Studio 16 2019"
      CONFIG: Release
      ARCH_ARG: "-A x64"

# install dependencies; cmake, python (for diligent)
install:
  - set CMAKE_URL="https://github.com/Kitware/CMake/releases/download/v3.19.3/cmake-3.19.3-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake
  - set PATH=C:\projects\deps\cmake\bin;C:\Python37;%PATH%
  - cmake --version
  - python --version

clone_script:
  - cmd: git clone --recursive -q --branch=main https://github.com/PatrickTorgerson/Envy.git C:\projects\envy

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"